### PR TITLE
Desktop version (PR)

### PR DESCRIPTION
**Pull request by Nelofarzabi**
The Requirements of this project were as follows: 

- To build a Desktop Version of the Portfolio similar to the one provided in the figma design.
- To use media queries in the CSS file to make the desktop version.
- To use Grid and Flexbox to layout elements on the page.

# Outcome

- Successfully built a desktop version.

### CODE REVIEW

**Comment by huseyinbiyik** [comment]
Hi @Nelofarzabi 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

Alt Text

## Invalid Code Review Request

⚠️ You have submitted a project, that seems following Git-flow instead of Github Flow. Kindly follow the correct flow as requested [here](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/github_flow.md). 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Nelofarzabi** [comment]
Hi @huseyinbiyik I deleted the dev branch inorder to follow the Github-flow but after deleting the dev branch I noticed that the pull request closed. So I am there resubmitting this pull request and awaiting your advice.

**Comment by huseyinbiyik** [comment]
Since you were using dev branch instead of the main till now, you can rename your dev branch as the main and remove the initial main branch.

**Comment by Nelofarzabi** [comment]
Hi @huseyinbiyik I deleted the dev branch and made the main branch my default branch. Then immediately after i deleted the dev branch i noticed that my PR was closed. I dont know what to do next since i am not allowed to create a new pull request

**Comment by mukhammadrizooff** [comment]
@Nelofarzabi Please `rename` your branch to `main` and open this `Pull Request` again 

image

image

**Comment by Nelofarzabi** [comment]
> @Nelofarzabi Please `rename` your branch to `main` and open this `Pull Request` again
> 
> image
> 
> image
> 
> image

WHhich branch should i rename? I already have a main branch which is my default branch. Kindly explain

**Comment by Nelofarzabi** [comment]
Hello @mukhammadrizooff I already have a main branch which is my default branch. Which branch do you want me to rename? Kindly explain

**Comment by mukhammadrizooff** [comment]
@Nelofarzabi 

image

**Pull request closed without merging**
